### PR TITLE
Fix the build id search... kinda

### LINKED ISSUE #87: Using the build id search box breaks filtering
Whenever there's a string entered in the build id search box, two things happen:
1/ you can't filter on any other filter (selecting any other filter should reset the build id search box)
2/ it doesn't filter on the build id at all

### PR DESCRIPTION
**Pull request by magopian**
Fixes #87

screenshot from 2017-06-02 16-03-29

See #90 for why this isn't totally fixing the build id search.

### CODE REVIEW

File: ui/Main.elm [hunk 1]
```diff
@@ -59,35 +59,41 @@ update msg ({ filterValues } as model) =
...
         UpdateFilter newFilter ->
             let
+                noFilters =
+                    { model
+                        | productFilter = "all"
+                        , versionFilter = "all"
+                        , platformFilter = "all"
+                        , channelFilter = "all"
+                        , localeFilter = "all"
+                        , buildIdFilter = ""
```
Comment (n1k0) [inline ui/Main.elm]: Side remark: it really feels like we should have a `Filters` type, and some `init` function for it. We could then have `FilterMsg`, an update function for it, and a dedicated module. 

Could be done in a next PR though.

**Comment by magopian** [comment]
Yeah we definitely need to debounce it, I submitted #89 for just that.

File: ui/Main.elm (hunk 1 above)
Comment (magopian) [inline ui/Main.elm]: Indeed! I had submitted #65 some time ago, but didn't get to it yet, as it seems less urgent
